// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CardIntent is any intent that renders a card (everything but "none").
 */
export type CardIntent = IntentKey;

/**
 * IntentKey is every card type plus "none" (no confident match).
 */
export enum IntentKey {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    IntentEvent = "event",
    IntentReminder = "reminder",
    IntentTodo = "todo",
    IntentTimer = "timer",
    IntentHabit = "habit",
    IntentColor = "color",
    IntentSplit = "split",
    IntentExpense = "expense",
    IntentConvert = "convert",
    IntentCalc = "calc",
    IntentTravel = "travel",
    IntentPoll = "poll",
    IntentContact = "contact",
    IntentLink = "link",
    IntentCountdown = "countdown",
    IntentTimezone = "timezone",
    IntentRandom = "random",
    IntentGoal = "goal",
    IntentNote = "note",
    IntentNone = "none",
};

export interface SavedItem {
    "id": string;
    "intent": CardIntent;
    "summary": string;
    "text": string;
    "createdAt": number;
}
