// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotesService exposes the card store to the frontend (mirrors the
 * localStorage API in frontend/src/lib/savedItems.ts). The frontend keeps
 * working unchanged: same shapes, Go-owned IDs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes one card. Unknown IDs are not an error.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1433266871, id);
}

/**
 * List returns all saved cards, oldest first.
 */
export function List(): $CancellablePromise<$models.SavedItem[] | null> {
    return $Call.ByID(1901722660);
}

/**
 * Save inserts (empty ID) or updates one card and returns the stored copy.
 */
export function Save(item: $models.SavedItem): $CancellablePromise<$models.SavedItem> {
    return $Call.ByID(2486875065, item);
}
